<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="0" failed="5" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-11-08T15:30:27 IST" name="Default suite" finished-at="2022-11-08T15:33:33 IST" duration-ms="186703">
    <groups>
    </groups>
    <test started-at="2022-11-08T15:30:27 IST" name="Default test" finished-at="2022-11-08T15:33:33 IST" duration-ms="186703">
      <class name="Test.HomePageTest">
        <test-method is-config="true" signature="triggerDriver()[pri:0, instance:Test.HomePageTest@22c86919]" started-at="2022-11-08T15:30:27 IST" name="triggerDriver" finished-at="2022-11-08T15:30:39 IST" duration-ms="12064" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- triggerDriver -->
        <test-method signature="UploadProfileImage()[pri:1, instance:Test.HomePageTest@22c86919]" started-at="2022-11-08T15:30:39 IST" name="UploadProfileImage" finished-at="2022-11-08T15:31:15 IST" duration-ms="36735" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Santosh Thakare | LinkedIn] but found [(58) Santosh Thakare | LinkedIn]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Santosh Thakare | LinkedIn] but found [(58) Santosh Thakare | LinkedIn]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at Test.HomePageTest.UploadProfileImage(HomePageTest.java:47)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UploadProfileImage -->
        <test-method is-config="true" signature="terminateDriver()[pri:0, instance:Test.HomePageTest@22c86919]" started-at="2022-11-08T15:31:15 IST" name="terminateDriver" finished-at="2022-11-08T15:31:23 IST" duration-ms="7427" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- terminateDriver -->
        <test-method is-config="true" signature="triggerDriver()[pri:0, instance:Test.HomePageTest@22c86919]" started-at="2022-11-08T15:31:23 IST" name="triggerDriver" finished-at="2022-11-08T15:31:28 IST" duration-ms="4632" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- triggerDriver -->
        <test-method signature="UploadImage()[pri:2, instance:Test.HomePageTest@22c86919]" started-at="2022-11-08T15:31:28 IST" name="UploadImage" finished-at="2022-11-08T15:31:50 IST" duration-ms="22914" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Feed | LinkedIn] but found [(58) Feed | LinkedIn]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Feed | LinkedIn] but found [(58) Feed | LinkedIn]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at Test.HomePageTest.UploadImage(HomePageTest.java:61)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UploadImage -->
        <test-method is-config="true" signature="terminateDriver()[pri:0, instance:Test.HomePageTest@22c86919]" started-at="2022-11-08T15:31:50 IST" name="terminateDriver" finished-at="2022-11-08T15:31:58 IST" duration-ms="7300" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- terminateDriver -->
        <test-method is-config="true" signature="triggerDriver()[pri:0, instance:Test.HomePageTest@22c86919]" started-at="2022-11-08T15:31:58 IST" name="triggerDriver" finished-at="2022-11-08T15:32:03 IST" duration-ms="5194" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- triggerDriver -->
        <test-method signature="CommentPost()[pri:3, instance:Test.HomePageTest@22c86919]" started-at="2022-11-08T15:32:03 IST" name="CommentPost" finished-at="2022-11-08T15:32:17 IST" duration-ms="14301" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Feed | LinkedIn] but found [(58) Feed | LinkedIn]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Feed | LinkedIn] but found [(58) Feed | LinkedIn]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at Test.HomePageTest.CommentPost(HomePageTest.java:76)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CommentPost -->
        <test-method is-config="true" signature="terminateDriver()[pri:0, instance:Test.HomePageTest@22c86919]" started-at="2022-11-08T15:32:17 IST" name="terminateDriver" finished-at="2022-11-08T15:32:25 IST" duration-ms="7383" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- terminateDriver -->
        <test-method is-config="true" signature="triggerDriver()[pri:0, instance:Test.HomePageTest@22c86919]" started-at="2022-11-08T15:32:25 IST" name="triggerDriver" finished-at="2022-11-08T15:32:30 IST" duration-ms="5021" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- triggerDriver -->
        <test-method signature="RandomCommentPost()[pri:4, instance:Test.HomePageTest@22c86919]" started-at="2022-11-08T15:32:30 IST" name="RandomCommentPost" finished-at="2022-11-08T15:33:02 IST" duration-ms="32185" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Feed | LinkedIn] but found [(58) Feed | LinkedIn]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Feed | LinkedIn] but found [(58) Feed | LinkedIn]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at Test.HomePageTest.RandomCommentPost(HomePageTest.java:92)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RandomCommentPost -->
        <test-method is-config="true" signature="terminateDriver()[pri:0, instance:Test.HomePageTest@22c86919]" started-at="2022-11-08T15:33:02 IST" name="terminateDriver" finished-at="2022-11-08T15:33:09 IST" duration-ms="7325" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- terminateDriver -->
        <test-method is-config="true" signature="triggerDriver()[pri:0, instance:Test.HomePageTest@22c86919]" started-at="2022-11-08T15:33:09 IST" name="triggerDriver" finished-at="2022-11-08T15:33:15 IST" duration-ms="5347" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- triggerDriver -->
        <test-method signature="likePost()[pri:5, instance:Test.HomePageTest@22c86919]" started-at="2022-11-08T15:33:15 IST" name="likePost" finished-at="2022-11-08T15:33:26 IST" duration-ms="11421" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<(58) Feed | LinkedIn> but was:<Feed | LinkedIn>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<(58) Feed | LinkedIn> but was:<Feed | LinkedIn>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:82)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:87)
at Test.HomePageTest.likePost(HomePageTest.java:109)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- likePost -->
        <test-method is-config="true" signature="terminateDriver()[pri:0, instance:Test.HomePageTest@22c86919]" started-at="2022-11-08T15:33:26 IST" name="terminateDriver" finished-at="2022-11-08T15:33:33 IST" duration-ms="7370" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- terminateDriver -->
      </class> <!-- Test.HomePageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
